# Dataset paths
visual_feature_root: './ETFG/MEAD_features/visual/'  # Directory containing ldmk and face_embed features
audio_feature_root: './ETFG/MEAD_features/audio/'    # Directory containing mfcc features

# Dataset configuration
train_subjects: ['M007', 'M009', 'M011', 'M012', 'M013', 'M019', 'M022', 'M023', 'M024', 'M025', 'M026',
                 'M027', 'M028', 'M029', 'M032', 'M033', 'M034', 'M035', 'M037', 'M039', 'M040', 'M041',
                 'M042', 'W014', 'W017', 'W018', 'W019', 'W021', 'W023', 'W024', 'W025',
                 'W026', 'W028', 'W029', 'W033', 'W035', 'W036', 'W037', 'W038', 'W040']
val_subjects: ['M005', 'M031', 'W016', 'W011']
test_subjects: ['W015', 'M003', 'M030', 'W009']
emotion_labels: ['angry', 'contempt', 'disgusted', 'fear', 'happy', 'sad', 'surprised', 'neutral']
intensity_level: 'level_3'

# Model configuration
feature_type: 'face_embed'
batch_size: 256
num_workers: 0
max_epochs: 300
learning_rate: 0.0001
hidden_dim: 128
num_layers: 3
emotion_embedding_dim: 32
architecture_type: 'encoder_only'  # 'encoder_only' or 'encoder_decoder'

# Logging configuration
log_name: 'face_embed_level3'
lightning_log_root: './ETFG/lightning_logs'  # Root directory for lightning logs



