# Feature type to use ('ldmk' or 'face_embed')
feature_type: 'ldmk'

# Paths to model checkpoints
etfg_checkpoint: '/Users/xiaokeai/Documents/HKUST/projects/grace/grace_emo/ETFG/lightning_logs/face_embed/version_14/checkpoints/face_embed-epoch=07-val_loss=0.06.ckpt'
motor_checkpoint: '/Users/xiaokeai/Documents/HKUST/projects/grace/grace_emo/emotion/motor_prediction/lightning_logs/face_embed/lightning_logs/version_10/checkpoints/epoch=27-step=700.ckpt'

# Path to save results
save_path: './results_level3'

# Dataset configuration
dataset:
  # Paths to feature directories
  visual_root_dir: '/Users/xiaokeai/Documents/HKUST/projects/grace/grace_emo/ETFG/MEAD_features/visual/'
  audio_root_dir: '/Users/xiaokeai/Documents/HKUST/projects/grace/grace_emo/ETFG/MEAD_features/audio/'

  grace_data_root_dir: '/Users/xiaokeai/Documents/HKUST/projects/grace/grace_emo/dataset/updated_gau_1000_features/'
  # List of subjects to include
  subjects: ['W015', 'M003', 'M030', 'W009']
  # List of emotion labels to include
  emotion_labels: ['angry', 'contempt', 'disgusted', 'fear', 'happy', 'sad', 'surprised', 'neutral']

  # Intensity level to use
  intensity_level: 'level_3'